# Generated by Django 4.2.5 on 2023-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
