# Generated by Django 4.2.5 on 2023-10-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_car_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.color'),
        ),
    ]
